# This workflow builds and pushes a Docker image to GitHub Container Registry on push to main
# Docs: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
